### ISSUE TITLE
Not installing on windows 10

### ISSUE THREAD

**Issue by zareena11** [stephenwvickers/node-windows-service#3]
if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:401:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:356:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\u0065650\AppData\Roaming\npm\node_modules\windows-service
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "windows-service"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE

npm ERR! windows-service@1.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the windows-service@1.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the windows-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs windows-service
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls windows-service
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\u0065650\AppData\Roaming\npm\node_modules\npm-debug.log

**Comment by stephenwvickers** [comment]
Hi,

You first issue is clearly printed in the output, you should read it properly before raising an issue:

```
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
```

Secondly, the modules docs state:

```
NOTE This module has been deprecated in favour of the os-service module, please use that module instead. The two modules differ in that the add() and remove() functions require a callback.
```

Steve
